create table person(
                       person_id int
                           generated by default as identity
                           primary key ,
                       name varchar not null unique ,
                       date varchar not null
);

insert into person(name, date_of_birth) VALUES ('Admin', 1900-01-01);

create table book (
                      book_id int generated by default as identity primary key ,
                      person_id int default 1 references person(person_id) on delete set default ,
                      title varchar(100) not null,
                      author varchar(100) not null ,
                      year int check ( year > 0 )

    );